version: 2.1

# https://circleci.com/docs/2.0/language-android/
orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          # Stores mobile apk for local testing
          path: app/build/outputs/apk
          destination: mobile-apk